In [2]:
import pandas as pd
house_baoan = pd.read_excel('house_baoan.xls', index_col=None)
house_baoan.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,920.0,77188,天悦龙庭二期,3室2厅,119.19,西南,精装,有电梯,宝安中心,中,2005,塔楼,13
1,340.0,51909,大益广场,2室2厅,65.50,西南,精装,有电梯,西乡,低,2002,板塔结合,160
2,660.0,73884,中熙香缇湾,4室2厅,89.33,西南,精装,有电梯,西乡,中,2009,板塔结合,226
3,1150.0,76657,深业新岸线三期,4室1厅,150.02,东南,精装,有电梯,宝安中心,中,2008,塔楼,29
4,570.0,52127,碧海富通城一期,3室2厅,109.35,南,精装,有电梯,碧海,中,2006,板塔结合,54

In [3]:
house_futian = pd.read_excel('house_futian.xls', index_col=None)
house_futian.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,588.0,66090,金海湾花园,2室2厅,88.97,东南,简装,有电梯,上下沙,低,2001,板塔结合,156
1,500.0,66086,益田村,3室2厅,75.66,南,其他,无电梯,石厦,中,1995,板塔结合,87
2,565.0,58483,景新花园,4室2厅,96.61,南,简装,有电梯,景田,低,1996,塔楼,96
3,425.0,54481,众孚大厦,2室2厅,78.01,南,其他,有电梯,石厦,高,2002,板塔结合,343
4,428.0,53056,嘉洲豪园,2室1厅,80.67,东北,简装,有电梯,新洲,低,2001,板塔结合,229

In [4]:
house_longgang = pd.read_excel('house_longgang.xls', index_col=None)
house_longgang.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,335.0,38837,中海康城国际一期,3室1厅,86.26,西北,其他,有电梯,大运新城,高,2011,板楼,221
1,300.0,41380,中海康城花园二期,2室1厅,72.50,北,精装,有电梯,大运新城,低,2011,塔楼,221
2,485.0,56560,星河时代,3室1厅,85.75,南,精装,有电梯,大运新城,低,2012,塔楼,1197
3,189.0,34327,德福花园,2室2厅,55.06,西南,其他,无电梯,布吉街,高,1998,板塔结合,542
4,650.0,43724,万科城四期,5室2厅,148.66,南,其他,有电梯,坂田,低,2008,板塔结合,144

In [5]:
house_longhua = pd.read_excel('house_longhua.xls', index_col=None)
house_longhua.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,376,55246,潜龙鑫茂花园B区,2室2厅,68.06,北,精装,有电梯,民治,高,2006,板塔结合,66
1,350,43783,劲力城市明珠,3室1厅,79.94,东南,精装,有电梯,龙华中心,中,2005,板塔结合,60
2,670,75248,万科金域华府,3室2厅,89.04,西南,精装,有电梯,深圳北站,高,2010,板塔结合,365
3,670,75256,万科金域华府,3室2厅,89.03,西南,精装,有电梯,深圳北站,中,2010,板塔结合,276
4,560,40984,锦绣江南三期,4室1厅,136.64,东南,简装,有电梯,深圳北站,低,2005,板楼,12

In [6]:
house_luohu = pd.read_excel('house_luohu.xls', index_col=None)
house_luohu.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,246.0,47427,铂金时代罗湖,2室1厅,51.87,北,精装,有电梯,罗湖口岸,低,2008,板塔结合,276
1,220.0,57819,新天地名居,1室1厅,38.05,北,精装,有电梯,黄贝岭,中,2005,板塔结合,112
2,372.0,54165,翠盈嘉园,2室1厅,68.68,东 北,精装,有电梯,洪湖,中,2002,板塔结合,57
3,640.0,66841,缤纷时代家园,3室2厅,95.75,东南 南,精装,有电梯,螺岭,高,2004,板塔结合,183
4,355.0,46448,玉雅居,3室1厅,76.43,南,精装,有电梯,莲塘,中,1998,板塔结合,39

In [7]:
house_nanshan = pd.read_excel('house_nanshan.xls', index_col=None)
house_nanshan.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,1130.0,84398,海月花园二期,3室2厅,133.89,南 北,其他,有电梯,蛇口,高,2003,板塔结合,23
1,785.0,71749,缤纷假日豪园,3室2厅,109.41,东南,精装,有电梯,南山中心,低,2001,板塔结合,95
2,305.0,67078,美丽湾国际公寓,2室1厅,45.47,北,其他,有电梯,南山中心,高,2007,塔楼,72
3,500.0,78004,向南瑞峰花园,3室1厅,64.10,西,精装,有电梯,南山中心,低,2011,板塔结合,82
4,445.0,62047,海典居,2室2厅,71.72,东,其他,有电梯,南山中心,中,1999,板塔结合,33

In [8]:
house_yantian = pd.read_excel('house_yantian.xls', index_col=None)
house_yantian.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow
0,420.0,47340,中海半山溪谷花园,3室2厅,88.72,西北,精装,有电梯,盐田港,中,2008,板塔结合,104
1,480.0,44396,中海半山溪谷花园,4室2厅,108.12,东南,精装,有电梯,盐田港,高,2008,板塔结合,39
2,810.0,54130,海山道1号,4室2厅,149.64,东南,其他,有电梯,沙头角,低,2011,塔楼,19
3,190.0,36539,金水湾御园,2室1厅,52.00,西北,其他,有电梯,盐田港,高,2008,塔楼,194
4,153.0,41644,福苑,1室1厅,36.74,西北,其他,有电梯,沙头角,高,2001,板塔结合,24

In [9]:
house_baoan['city'] = '宝安'
house_futian['city'] = '福田'
house_longgang['city'] = '龙岗'
house_longhua['city'] = '龙华'
house_luohu['city'] = '罗湖'
house_nanshan['city'] = '南山'
house_yantian['city'] = '盐田'

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow,city
0,420.0,47340,中海半山溪谷花园,3室2厅,88.72,西北,精装,有电梯,盐田港,中,2008,板塔结合,104,盐田
1,480.0,44396,中海半山溪谷花园,4室2厅,108.12,东南,精装,有电梯,盐田港,高,2008,板塔结合,39,盐田
2,810.0,54130,海山道1号,4室2厅,149.64,东南,其他,有电梯,沙头角,低,2011,塔楼,19,盐田
3,190.0,36539,金水湾御园,2室1厅,52.00,西北,其他,有电梯,盐田港,高,2008,塔楼,194,盐田
4,153.0,41644,福苑,1室1厅,36.74,西北,其他,有电梯,沙头角,高,2001,板塔结合,24,盐田

In [11]:
house = pd.concat([house_baoan,house_futian,house_longgang,house_longhua,house_luohu,house_nanshan,house_yantian],axis=0,ignore_index=True)
house.head()

,totalprice,unitprice,position,rooms,size,orientation,decoration,elevator,area,height,year,buildtype,follow,city
0,920.0,77188,天悦龙庭二期,3室2厅,119.19,西南,精装,有电梯,宝安中心,中,2005,塔楼,13,宝安
1,340.0,51909,大益广场,2室2厅,65.50,西南,精装,有电梯,西乡,低,2002,板塔结合,160,宝安
2,660.0,73884,中熙香缇湾,4室2厅,89.33,西南,精装,有电梯,西乡,中,2009,板塔结合,226,宝安
3,1150.0,76657,深业新岸线三期,4室1厅,150.02,东南,精装,有电梯,宝安中心,中,2008,塔楼,29,宝安
4,570.0,52127,碧海富通城一期,3室2厅,109.35,南,精装,有电梯,碧海,中,2006,板塔结合,54,宝安

In [12]:
house.to_excel('house.xls',sheet_name='biubiu')