In [1]:
import requests
import requests
import time
from lxml import etree

In [2]:
#设置列表页URL的固定部分
url='http://gz.lianjia.com/chengjiao/'
#设置页面页的可变部分
page=('pg')
#设置请求头部信息
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
'Accept':'text/html;q=0.9,*/*;q=0.8',
'Accept-Charset':'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
'Accept-Encoding':'gzip',
'Connection':'close',
'Referer':'http://www.baidu.com/link?url=_andhfsjjjKRgEWkj7i9cFmYYGsisrnm2A-TN3XZDQXxvGsM9k9ZZSnikW2Yds4s&amp;amp;wd=&amp;amp;eqid=c3435a7d00146bd600000003582bfd1f'
}
for i in range(1,80):
    if i == 1:
        i=str(i)
        a=(url+page+i+'/')
        r=requests.get(url=a,headers=headers)
        html=r.content
    else:
        i=str(i)
        a=(url+page+i+'/')
        r=requests.get(url=a,headers=headers)
        html2=r.content
        html = html + html2
    #每次间隔0.5秒
    time.sleep(0.5)
encoding=requests.get(url,headers=headers).encoding
lj=etree.HTML(html,parser=etree.HTMLParser(encoding=encoding))
#提取房源总价
price=lj.xpath('//div[@class="totalPrice"]')

tp=[]
for a in price:
    totalPrice=a.xpath('.//span/text()')[0]
    tp.append(totalPrice)
for p in tp[:10]:
    print(p)

190
140.5
158
145
304
630
114.8
115.5
200
135

In [3]:
#提取房源单价
price=lj.xpath('//div[@class="unitPrice"]')

up=[]
for a in price:
    totalPrice=a.xpath('.//span/text()')[0]
    up.append(totalPrice)
for p in up[:10]:
    print(p)

24517
23734
23853
36840
33407
46667
36854
15822
33015
26492

In [4]:
#提取房源信息
houseInfo=lj.xpath('//div[@class="houseInfo"]')

hi=[]
for b in houseInfo:
    house=b.xpath('.//text()')[0]
    hi.append(house)
for i in hi[:10]:
    print(i)

东北 | 精装 | 有电梯
南 | 精装 | 无电梯
东 | 精装 | 无电梯
南 | 其他
南 | 其他 | 有电梯
南 | 其他 | 有电梯
南 | 其他 | 无电梯
南 | 其他
东 东南 | 简装 | 无电梯
南 | 简装 | 无电梯

In [5]:
# 提取位置信息
positionInfo=lj.xpath('//div[@class="positionInfo"]')

pi=[]
for b in positionInfo:
    house=b.xpath('.//text()')[0]
    pi.append(house)
for i in pi[:10]:
    print(i)

低楼层(共18层) 塔楼
中楼层(共7层) 1995年建塔楼
高楼层(共6层) 1998年建塔楼
低楼层(共8层) 塔楼
高楼层(共25层) 2009年建塔楼
高楼层(共34层) 2008年建塔楼
高楼层(共8层) 塔楼
高楼层(共5层) 板楼
中楼层(共9层) 1997年建塔楼
低楼层(共6层) 板楼

In [6]:
#导入pandas库
import pandas as pd
#创建数据表
house=pd.DataFrame({'unitprice':up,'totalprice':tp,'houseinfo':hi,'positioninfo':pi})
#查看数据表的内容
house.head()

  unitprice totalprice      houseinfo        positioninfo
0     24517        190  东北 | 精装 | 有电梯        低楼层(共18层) 塔楼
1     23734      140.5   南 | 精装 | 无电梯   中楼层(共7层) 1995年建塔楼
2     23853        158   东 | 精装 | 无电梯   高楼层(共6层) 1998年建塔楼
3     36840        145         南 | 其他         低楼层(共8层) 塔楼
4     33407        304   南 | 其他 | 有电梯  高楼层(共25层) 2009年建塔楼

In [7]:
#对房源信息进行分列
houseinfo_split = pd.DataFrame((x.split('|') for x in house.houseinfo),index=house.index,columns=['chaoxiang','zhuangxiu','dianti'])
houseinfo_split.head()

  chaoxiang zhuangxiu dianti
0       东北        精装     有电梯
1        南        精装     无电梯
2        东        精装     无电梯
3        南         其他   None
4        南        其他     有电梯

In [8]:
#将分列结果拼接回原数据表
house=pd.merge(house,houseinfo_split,right_index=True, left_index=True)
house.head(20)

,unitprice,totalprice,houseinfo,positioninfo,chaoxiang,zhuangxiu,dianti
0,24517,190,东北 | 精装 | 有电梯,低楼层(共18层) 塔楼,东北,精装,有电梯
1,23734,140.5,南 | 精装 | 无电梯,中楼层(共7层) 1995年建塔楼,南,精装,无电梯
2,23853,158,东 | 精装 | 无电梯,高楼层(共6层) 1998年建塔楼,东,精装,无电梯
3,36840,145,南 | 其他,低楼层(共8层) 塔楼,南,其他,None
4,33407,304,南 | 其他 | 有电梯,高楼层(共25层) 2009年建塔楼,南,其他,有电梯
5,46667,630,南 | 其他 | 有电梯,高楼层(共34层) 2008年建塔楼,南,其他,有电梯
6,36854,114.8,南 | 其他 | 无电梯,高楼层(共8层) 塔楼,南,其他,无电梯
7,15822,115.5,南 | 其他,高楼层(共5层) 板楼,南,其他,None
8,33015,200,东 东南 | 简装 | 无电梯,中楼层(共9层) 1997年建塔楼,东 东南,简装,无电梯
9,26492,135,南 | 简装 | 无电梯,低楼层(共6层) 板楼,南,简装,无电梯
10,38818,168,西南 | 其他 | 无电梯,中楼层(共5层) 1980年建板楼,西南,其他,无电梯
11,45298,366,北 | 其他 | 有电梯,中楼层(共32层) 1999年建塔楼,北,其他,有电梯
12,65239,615,西南 | 简装 | 有电梯,中楼层(共31层) 2000年建塔楼,西南,简装,有电梯
13,32639,166,东南 | 其他 | 无电梯,中楼层(共5层) 板楼,东南,其他,无电梯
14,34329,215,东南 | 其他 | 有电梯,中楼层(共11层) 2001年建塔楼,东南,其他,有电梯
15,35073,242,东南 | 其他 | 有电梯,中楼层(共32层) 塔楼,东南,其他,有电梯
16,74124,615,南 北 | 精装 | 有电梯,中楼层(共29层) 2010年建塔楼,南 北,精装,有电梯
17,31353,172,南 | 简装 | 无电梯,低楼层(共9层) 塔楼,南,简装,无电梯
18,44920,271,南 | 精装 | 有电梯,高楼层(共23层) 2002年建塔楼,南,精装,有电梯
19,28353,185,东南 | 简装 | 无电梯,低楼层(共7层) 1998年建塔楼,东南,简装,无电梯

In [9]:
#对位置信息进行分列
import re
positioninfo_split = pd.DataFrame((re.split(r"楼.+\)", x, maxsplit=0)[0] for x in house.positioninfo),index=house.index,columns=['louceng'])
positioninfo_split.head()

  louceng
0       低
1       中
2       高
3       低
4       高

In [10]:
house=pd.merge(house,positioninfo_split,right_index=True, left_index=True)
house.head(20)

,unitprice,totalprice,houseinfo,positioninfo,chaoxiang,zhuangxiu,dianti,louceng
0,24517,190,东北 | 精装 | 有电梯,低楼层(共18层) 塔楼,东北,精装,有电梯,低
1,23734,140.5,南 | 精装 | 无电梯,中楼层(共7层) 1995年建塔楼,南,精装,无电梯,中
2,23853,158,东 | 精装 | 无电梯,高楼层(共6层) 1998年建塔楼,东,精装,无电梯,高
3,36840,145,南 | 其他,低楼层(共8层) 塔楼,南,其他,None,低
4,33407,304,南 | 其他 | 有电梯,高楼层(共25层) 2009年建塔楼,南,其他,有电梯,高
5,46667,630,南 | 其他 | 有电梯,高楼层(共34层) 2008年建塔楼,南,其他,有电梯,高
6,36854,114.8,南 | 其他 | 无电梯,高楼层(共8层) 塔楼,南,其他,无电梯,高
7,15822,115.5,南 | 其他,高楼层(共5层) 板楼,南,其他,None,高
8,33015,200,东 东南 | 简装 | 无电梯,中楼层(共9层) 1997年建塔楼,东 东南,简装,无电梯,中
9,26492,135,南 | 简装 | 无电梯,低楼层(共6层) 板楼,南,简装,无电梯,低
10,38818,168,西南 | 其他 | 无电梯,中楼层(共5层) 1980年建板楼,西南,其他,无电梯,中
11,45298,366,北 | 其他 | 有电梯,中楼层(共32层) 1999年建塔楼,北,其他,有电梯,中
12,65239,615,西南 | 简装 | 有电梯,中楼层(共31层) 2000年建塔楼,西南,简装,有电梯,中
13,32639,166,东南 | 其他 | 无电梯,中楼层(共5层) 板楼,东南,其他,无电梯,中
14,34329,215,东南 | 其他 | 有电梯,中楼层(共11层) 2001年建塔楼,东南,其他,有电梯,中
15,35073,242,东南 | 其他 | 有电梯,中楼层(共32层) 塔楼,东南,其他,有电梯,中
16,74124,615,南 北 | 精装 | 有电梯,中楼层(共29层) 2010年建塔楼,南 北,精装,有电梯,中
17,31353,172,南 | 简装 | 无电梯,低楼层(共9层) 塔楼,南,简装,无电梯,低
18,44920,271,南 | 精装 | 有电梯,高楼层(共23层) 2002年建塔楼,南,精装,有电梯,高
19,28353,185,东南 | 简装 | 无电梯,低楼层(共7层) 1998年建塔楼,东南,简装,无电梯,低

In [11]:
# 提取房名信息
housingInfo=lj.xpath('//div[@class="title"]')

hoi=[]
for b in housingInfo:
    hou=b.xpath('.//a/text()')
    hoi.append(hou)
hoi = [x[0] for x in hoi if x!=[]]
hoi = [x for x in hoi if x!='去登录']
for i in hoi[:10]:
    print(i)

越秀岭南雅筑 2室2厅 77.5平米
富丽家园乳芳园 2室1厅 59.2平米
远景新苑 3室1厅 66.24平米
六榕路福泉一巷 2室1厅 39.36平米
万科新里程 3室2厅 91平米
荔港南湾 4室2厅 135平米
东风西路广雅前街 2室1厅 31.15平米
环城西路工农大街 3室1厅 73平米
棠德花园 2室1厅 60.58平米
鹤洞路鹤建里 2室1厅 50.96平米

In [12]:
housingInfo=pd.DataFrame({'allinfo':hoi})
#查看数据表的内容
housingInfo.head()

                allinfo
0    越秀岭南雅筑 2室2厅 77.5平米
1   富丽家园乳芳园 2室1厅 59.2平米
2     远景新苑 3室1厅 66.24平米
3  六榕路福泉一巷 2室1厅 39.36平米
4       万科新里程 3室2厅 91平米

In [13]:
housinginfo_split = pd.DataFrame((x.split(' ') for x in housingInfo.allinfo),index=housingInfo.index,columns=['xiaoqu','huxing','daxiao'])
housinginfo_split.head()

    xiaoqu huxing   daxiao
0   越秀岭南雅筑   2室2厅   77.5平米
1  富丽家园乳芳园   2室1厅   59.2平米
2     远景新苑   3室1厅  66.24平米
3  六榕路福泉一巷   2室1厅  39.36平米
4    万科新里程   3室2厅     91平米

In [14]:
daxiao_split = pd.DataFrame((x.split('平米') for x in housinginfo_split.daxiao),index=housingInfo.index,columns=['size','a'])
daxiao_split.drop(['a'],axis=1,inplace=True)
daxiao_split.head()

    size
0   77.5
1   59.2
2  66.24
3  39.36
4     91

In [15]:
huxing_split = pd.DataFrame((re.split('["室","厅"]',x) for x in housinginfo_split.huxing),index=housingInfo.index,columns=['main_room','sub_room', 'a'])
huxing_split.drop(['a'],axis=1,inplace=True)
huxing_split.head()

  main_room sub_room
0         2        2
1         2        1
2         3        1
3         2        1
4         3        2

In [16]:
housinginfo_split.drop(['huxing','daxiao'],axis=1,inplace=True)
housinginfo_split.head()

    xiaoqu
0   越秀岭南雅筑
1  富丽家园乳芳园
2     远景新苑
3  六榕路福泉一巷
4    万科新里程

In [17]:
house=pd.merge(house,housinginfo_split,right_index=True, left_index=True)
house.head()

,unitprice,totalprice,houseinfo,positioninfo,chaoxiang,zhuangxiu,dianti,louceng,xiaoqu
0,24517,190,东北 | 精装 | 有电梯,低楼层(共18层) 塔楼,东北,精装,有电梯,低,越秀岭南雅筑
1,23734,140.5,南 | 精装 | 无电梯,中楼层(共7层) 1995年建塔楼,南,精装,无电梯,中,富丽家园乳芳园
2,23853,158,东 | 精装 | 无电梯,高楼层(共6层) 1998年建塔楼,东,精装,无电梯,高,远景新苑
3,36840,145,南 | 其他,低楼层(共8层) 塔楼,南,其他,None,低,六榕路福泉一巷
4,33407,304,南 | 其他 | 有电梯,高楼层(共25层) 2009年建塔楼,南,其他,有电梯,高,万科新里程

In [18]:
house=pd.merge(house,daxiao_split,right_index=True, left_index=True)
house.head()

,unitprice,totalprice,houseinfo,positioninfo,chaoxiang,zhuangxiu,dianti,louceng,xiaoqu,size
0,24517,190,东北 | 精装 | 有电梯,低楼层(共18层) 塔楼,东北,精装,有电梯,低,越秀岭南雅筑,77.5
1,23734,140.5,南 | 精装 | 无电梯,中楼层(共7层) 1995年建塔楼,南,精装,无电梯,中,富丽家园乳芳园,59.2
2,23853,158,东 | 精装 | 无电梯,高楼层(共6层) 1998年建塔楼,东,精装,无电梯,高,远景新苑,66.24
3,36840,145,南 | 其他,低楼层(共8层) 塔楼,南,其他,None,低,六榕路福泉一巷,39.36
4,33407,304,南 | 其他 | 有电梯,高楼层(共25层) 2009年建塔楼,南,其他,有电梯,高,万科新里程,91

In [19]:
house=pd.merge(house,huxing_split,right_index=True, left_index=True)
house.head()

,unitprice,totalprice,houseinfo,positioninfo,chaoxiang,zhuangxiu,dianti,louceng,xiaoqu,size,main_room,sub_room
0,24517,190,东北 | 精装 | 有电梯,低楼层(共18层) 塔楼,东北,精装,有电梯,低,越秀岭南雅筑,77.5,2,2
1,23734,140.5,南 | 精装 | 无电梯,中楼层(共7层) 1995年建塔楼,南,精装,无电梯,中,富丽家园乳芳园,59.2,2,1
2,23853,158,东 | 精装 | 无电梯,高楼层(共6层) 1998年建塔楼,东,精装,无电梯,高,远景新苑,66.24,3,1
3,36840,145,南 | 其他,低楼层(共8层) 塔楼,南,其他,None,低,六榕路福泉一巷,39.36,2,1
4,33407,304,南 | 其他 | 有电梯,高楼层(共25层) 2009年建塔楼,南,其他,有电梯,高,万科新里程,91,3,2

In [20]:
house['unitprice']=pd.to_numeric(house['unitprice'],errors='coerce')

In [21]:
house.dtypes

unitprice        int64
totalprice      object
houseinfo       object
positioninfo    object
chaoxiang       object
zhuangxiu       object
dianti          object
louceng         object
xiaoqu          object
size            object
main_room       object
sub_room        object
dtype: object

In [22]:
house['totalprice']=house['totalprice'].astype('float64')
house.dtypes

unitprice         int64
totalprice      float64
houseinfo        object
positioninfo     object
chaoxiang        object
zhuangxiu        object
dianti           object
louceng          object
xiaoqu           object
size             object
main_room        object
sub_room         object
dtype: object

In [23]:
house['size']=pd.to_numeric(house['size'],errors='coerce')
house['main_room']=pd.to_numeric(house['main_room'],errors='coerce')
house['sub_room']=pd.to_numeric(house['sub_room'],errors='coerce')

In [24]:
house.dtypes

unitprice         int64
totalprice      float64
houseinfo        object
positioninfo     object
chaoxiang        object
zhuangxiu        object
dianti           object
louceng          object
xiaoqu           object
size            float64
main_room       float64
sub_room        float64
dtype: object

In [25]:
house.to_csv("house.csv",encoding ="utf-8")

In [26]:
house.to_excel('house.xls',sheet_name='biubiu')